Check if scrambled before showing solve message
roice3/MagicCube5D pull request #2
Opened 2020-07-03 21:34 UTC by bonimy

* Add member `m_scrambled` to `CCube5D` which is set if a scramble of
  over 100 moves has occurred.
* Update `CCube5D::showSolvedMessage()` to check if `m_scrambled` is
  set. If not, the message will not be shown.

2020-07-03 21:44 UTC, roice3 requested changes
Hey Nelson, looks good but I think we also need to save this information to log files. As is, it will only work if the user solves the puzzle in one sitting. If they were to save their progress and reload it later (common scenario), the code won’t set this new scrambled variable to true and they won’t get the solved message.

2020-07-03 21:47 UTC, bonimy commented
Nice catch. I'll see what I can do. Also, hello again Roice, long time.

2020-07-04 00:34 UTC, bonimy commented
@roice3, the scramble state is now saved to log file.

2020-07-04 00:36 UTC, roice3 approved these changes
Thanks for the contribution! And nice to hear from you again :)

2020-07-04 03:11 UTC, merged